### ISSUE TITLE
The plugin should not show in the list of licenses

### ISSUE THREAD

**Issue by Benunc** [mathetos/give-receipt-attachments#11]
version 1.1.1 currently messes up the license handler for the free GiveWP plugin, indicating a need for a license. This needs to be resolved by changing the plugin author, or the Plugin URI, or the Plugin Author URL (or some combination of all three).

This is being handled in GiveWP core as well, but still may need addressing here.

**Comment by mathetos** [comment]
[Based on this Slack convo](https://givewp.slack.com/archives/C0FAGC83C/p1590002550022800), I updated the Plugin URI to a shortlink and we should be good to do now. 

[This commit](https://github.com/mathetos/give-receipt-attachments/commit/45c76cab1fcf9f0a47a1ec38ff097ece58c1044e#diff-662624c51816ee1368d3f911dd79ca07) resolves this.
